### ISSUE TITLE
Removed unused, undocumented and unneeded "update" action tag

### ISSUE THREAD

**Issue by GonzaloUlla** [sassoftware/viya4-iac-aws#109]
The `update` action of `viya` task currently has the exact same behavior of `install`.

There is no point in having duplicated actions, and code meant for "future growth" usually ends up being changed along the way.

Therefore, this action tag should be removed

**Comment by thpang** [comment]
Nope not going to remove the code base. That's how the development team on IAC works. Code goes in all the time that is not intended for modification and is simply not documented. Eventually `update` will have some differences vs `install` but not at this time.
