### ISSUE TITLE
Allow ability to specify which Availability Zones the subnets get created in

### ISSUE THREAD

**Issue by dahamr** [sassoftware/viya4-iac-aws#113]
When allowing IAC on AWS to create the subnets, IAC doesn't provide a mechanism by which to control which availability zones in the passed region/location should be used for the subnets.

This is critical for optimal network access when integrating with a customer's existing environment.

**Comment by jarpat** [comment]
The ability to control which AZs subnets get created in was implemented in #240 with the `subnet_azs` variable. Closing as superseded.
