### ISSUE TITLE
(IAC-567) Allow ability to enable encryption on volumes created by the IaC

### ISSUE THREAD

**Issue by sbralg** [sassoftware/viya4-iac-aws#115]
Add support to enable encryption for EBS and EFS storage volumes created by the IaC project.

**Comment by canpmh** [comment]
Wondering if it is absolutely necessary that the volume be created by IaC, or can the customer provide a previously created EFS endpoint and still benefit from this IaC enhancement?

AWS seems to use STunnel to facilitate the encryption:

- [AWS Doc - Encrypting Data in Transit]( https://docs.aws.amazon.com/efs/latest/ug/encryption-in-transit.html)
- [AWS Doc - Using EFS mount helper to mount EFS file systems](https://docs.aws.amazon.com/efs/latest/ug/efs-mount-helper.html)

**Comment by canpmh** [comment]
EFS encryption at rest is trivial to implement, through one simple code change in vms.tf, as shown below:

resource "aws_efs_file_system" "efs-fs" {
  count            = var.storage_type == "ha" ? 1 : 0
  creation_token   = "${var.prefix}-efs"
  performance_mode = var.efs_performance_mode
  **encrypted = true**
  tags             = merge(var.tags, { "Name": "${var.prefix}-efs" })
}

**Comment by dhoucgitter** [comment]
Support for AWS EBS and EFS encryption added under PR https://github.com/sassoftware/viya4-iac-aws/pull/183, it was first made available in the [5.5.0 - February 17, 2023](https://github.com/sassoftware/viya4-iac-aws/releases/tag/5.5.0) release.

**Comment by dhoucgitter** [comment]
Closing #115 as completed.
