### ISSUE TITLE
Delete resources script in Teraform

### ISSUE THREAD

**Issue by dilipmrajan9** [sassoftware/viya4-iac-aws#125]
Hi Team, 

Can we also include a terraform tear down script for removing all the resources created in an AWS account ?

**Comment by thpang** [comment]
You can run `terraform destroy ... ` and it'll clean up your environment on ALL cloud providers. If you could, clarify your question.

**Comment by dilipmrajan9** [comment]
I'm using the docker container to run terraform from a vm and hence not sure how terraform destroy would apply directly. I'm a CFN user not an expert on TF.

**Comment by thpang** [comment]
Please review this documentation on how to [Tear Down Resources](https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/user/DockerUsage.md#tear-down-resources) If that answers your question please close this issue. Thx.

**Comment by thpang** [comment]
@dilipmrajan9 were you able to delete your items?

**Comment by dilipmrajan9** [comment]
Thanks @thpang Havent had a chance to test it unfortunately. But let me close it out for the moment. Will reopen if I run into any issues.
