### ISSUE TITLE
feat: (IAC-284) Request to include AWS FSx for Lustre

### ISSUE THREAD

**Issue by dilipmrajan9** [sassoftware/viya4-iac-aws#128]
Customers looking to modernize already have existing infra with FSx for Lustre and it would be useful for Viya to include this FSx for Lustre. [Please take a look at SAS Grid architecture](https://docs.aws.amazon.com/eks/latest/userguide/fsx-csi.html

**Comment by sayeun** [comment]
Closing this as we are not pursuing FSx for Lustre in the IAC side of things at this time.  However, we added support for FSx for NetApp ONTAP since the iac-aws 7.2.0 release.

**Comment by j2clerck** [comment]
@sayeun does it mean that SAS does not recommend FSX for Lustre with SAS Viya and NetApp ONTAP is recommended ?
