### ISSUE TITLE
Attempting to destroy all resources times out with errors about subnet and igw

### ISSUE THREAD

**Issue by gwsas** [sassoftware/viya4-iac-aws#129]
### Terraform Version Details

Not sure how to run iac_tooling_version.sh from docker.  I don't have terraform installed locally.

Running this from docker

viya4-iac-aws  version -json

shows
```
{
  "terraform_version": "1.0.0",
  "platform": "linux_amd64",
  "provider_selections": {
    "registry.terraform.io/hashicorp/aws": "3.43.0",
    "registry.terraform.io/hashicorp/cloudinit": "2.2.0",
    "registry.terraform.io/hashicorp/external": "2.1.0",
    "registry.terraform.io/hashicorp/kubernetes": "2.2.0",
    "registry.terraform.io/hashicorp/local": "2.1.0",
    "registry.terraform.io/hashicorp/null": "3.1.0",
    "registry.terraform.io/hashicorp/random": "3.1.0",
    "registry.terraform.io/hashicorp/template": "2.2.0",
    "registry.terraform.io/terraform-aws-modules/http": "2.4.1"
  },
  "terraform_outdated": false
}
```

### Terraform Variable File Details

I don't think there is anything in my tfvars file that directly affects the resources that aren't being cleaned up, but can provide it if needed.

### Steps to Reproduce

I'm running this to destroy the aws resources

docker container run --rm --group-add root     --user $(id -u):$(id -g)     --env=KUBECONFIG=/workspace/${PREFIX}-eks-kubeconfig.conf     -v ~/aws/workspace:/workspace     -v ~/aws/workspace/.aws/:/.aws/     viya4-iac-aws     destroy     -auto-approve     -var-file /workspace/terraform.tfvars     -state /workspace/terraform.tfstate 

### Expected Behavior

Everything is destroyed.

### Actual Behavior

I always get timeouts for a subnet and internet gateway

Error: error deleting subnet (subnet-0a597f41719a2288f): timeout while waiting for state to become 'destroyed' (last state: 'pending', timeout: 20m0s)

 Error: Error waiting for internet gateway (igw-06cdc80727882f07b) to detach: timeout while waiting for state to become 'detached' (last state: 'detaching', timeout: 15m0s)

It doesn't matter if I wait days and try again, I still get these messages.

### Additional Context

In the AWS console, I can manually detach, then delete the internet gateway, igw-06cdc80727882f07b to get rid of it.

If I try to manually delete the subnet in the AWS console, I see

Subnets have network interfaces and cannot be deleted

If I go to the network interfaces area, there are 2 associated with my subnet, but neither can be deleted because it says they are in use.

Eventually, I can clean up the resources with the AWS console, but it's a lot of trial and error of tracking down what needs to be deleted/detached/etc. before something else can go.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thpang** [comment]
I am guessing you've deployed Viya 4 into the cluster. Have you removed the Viya 4 installation prior to running the `terraform destroy`?

**Comment by gwsas** [comment]
No, I didn't remove the Viya 4 deployment first.  I was hoping the "big hammer" of resource destruction would be sufficient to get rid of everything without an intermediate step of uninstalling the Viya 4 deployment.
I can try doing the baseline,viya,uninstall operation first with viya4-deployment first if that is the recommendation.

**Comment by thpang** [comment]
That is recommended.

**Comment by gwsas** [comment]
Yes, can confirm that first performing the uninstall via viya4-deployment allows a smooth destroy via viya4-iac-aws with no timeouts for subnet, igw, or other resources.

**Comment by thpang** [comment]
Perfect. Need to find a place in the docs that outlines the steps needed to windup and unwind the setup the IAC/DAC code bases performs. Closing this one. Take care.

**Comment by rocoll** [comment]
Just fyi…

In case you can’t do a clean uninstall using viya4-deployment (and tear down with terraform destroy), then the GEL Reaper project can help:
https://gitlab.sas.com/GEL/utilities/gel-reaper

It’s not perfect for all situations, but it works to keep our costs down when students neglect to clean up after running a workshop.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
