### ISSUE TITLE
Issue in running terraform after simplifying commands into docker

### ISSUE THREAD

**Issue by lorenzk1213** [sassoftware/viya4-iac-aws#134]
Hi,

I am attempting to build an AWS infra using viya4-iac-aws github project.

I have a docker container run command,, however this command is failing with the error message:
Couldn't set up logging tempfile: open /tmp/terraform-log465088132: permission denied

Command I used:

docker container run --rm --group-add root --user $(id -u):$(id -g) -v $HOME/.aws:/.aws -v $HOME/.ssh:/.ssh -v $HOME/viya4-iac-aws:/workspace --entrypoint terraform viya4-iac-aws

tried as well below
docker run --rm --group-add root --user $(id -u):$(id -g) -v $HOME/.aws:/.aws -v $HOME/.ssh:/.ssh -v $HOME/viya4-iac-aws:/workspace --entrypoint terraform viya4-iac-aws

Not sure why its saying something about /tmp. the permission of this folder is drwxrwxrwt
I am using Amazon Linux2 OS.

Pls advice,
Thanks in advance,

**Comment by thpang** [comment]
Who is the docker user you're running as? Is it root? You may want to run as a normal user. Again, not knowing what your system is like can't help much here. You may want to google the issue and/or check this [link](https://communities.sas.com/t5/SAS-Viya/Failed-to-create-remote-module-tmp-path-at-dir-tmp-root-ansible/m-p/643479) to see if that helps.

**Comment by lorenzk1213** [comment]
Please disregard, I just downloaded a new viya4-iac-aws package and rerun the steps. all good now.
