### ISSUE TITLE
fix: (IAC-700) cloud-init script not being invoked in IaC v5 with Managed Node Groups

### ISSUE THREAD

**Issue by canpmh** [sassoftware/viya4-iac-aws#139]
I built a cluster with the new v5 scripts, leveraging the new Managed Node Groups feature, but I'm not seeing the local NVME drives being striped and mounted to the node.  
 
I've included the usual on my node groups:   "custom_data" = "files/custom-data/additional_userdata.sh"

the first thing the script does is install a package:  _yum -y install nvme-cli mdadm_

The package is not present on the nodes, so perhaps the cloud-init script (additional_userdata.sh) is not getting invoked due to the change up from launch configurations to launch templates.   

For xRef:  I did post on the IAC channel:

<https://teams.microsoft.com/l/message/19:20dbddb515c540b3993a44c35a15a96b@thread.skype/1653427740352?tenantId=b1c14d5c-3625-45b3-a430-9552373a0c2f&amp;groupId=b88e8d40-08ab-45bb-9990-96459f0fda6d&amp;parentMessageId=1653427137215&amp;teamName=R&amp;D Viya Next&amp;channelName=Infrastructure as Code (IaC)&amp;createdTime=1653427740352>
 
I was able to take the core elements of the script, and run them on the node, and everything striped and mounted successfully!

**Comment by canpmh** [comment]
Adding the work around document I created.
[Updating an AWS Launch Template for an Auto Scaling Group.docx](https://github.com/sassoftware/viya4-iac-aws/files/8781196/Updating.an.AWS.Launch.Template.for.an.Auto.Scaling.Group.docx)

**Comment by canpmh** [comment]
A customer of mine used the following fix which seems to have worked, they added a new variable in locals.tf, **_pre_bootstrap_user_data_** to reference the NVME based shell script we want included into the cloud init process:

pre_bootstrap_user_data           = "${file("files/custom-data/additional_userdata.sh")}"

The place it before the existing line:

post_bootstrap_user_data          = "${file("files/custom-data/additional_userdata.sh")}"

Not sure why they didn't comment out the existing line, if it isn't doing anything.  I will try to test this next week when I build another cluster using AWS IAC.

**Comment by SelerityMichael** [comment]
Referring to the documentation of the underlying [EKS Terraform module](https://github.com/terraform-aws-modules/terraform-aws-eks/blob/master/docs/user_data.md), when using an EKS Managed Node Group and _not_ specifying an `ami_id` the only way to get user data injected is to use the `pre_bootstrap_user_data` variable.

Reading between the lines, it would appear that in this scenario the `post_bootstrap_user_data` variable doesn't do anything (which is what we have all experienced).
