### ISSUE TITLE
Viya-ark Pre Install Checker Reports Namespace Admin Permissions - Insufficient.

### ISSUE THREAD

**Issue by lorenzk1213** [sassoftware/viya4-iac-aws#140]
Hi,

We have used viya4-iac to deploy the AWS environment. and used viya4-deployment DAC to deploy the baseline components,
Right now, tried to run the viy4-ark pre-install checker,
My Viya-Ark Pre-Install Checker Reports indequate permission for the Namespace Admin,

![image](https://user-images.githubusercontent.com/104424321/170154399-e00adfad-0d55-47a0-b660-e863c1cf473a.png)

Can pls help on how to address this issue?

Thanks,

**Comment by thpang** [comment]
@kevinlinglesas I'll ask for some help here. Not sure what the tool is looking for. Thanks.

**Comment by kevinlinglesas** [comment]
@thpang , I need to check with the developer for specifics on the criteria being checked.  

@lorenzk1213,  are you seeing these results being inconsistent with what you know your namespace admin permissions are, or are you asking how to make the permissions adequate now that the tool has highlighted this?

**Comment by kevinlinglesas** [comment]
actually, this was answered in https://github.com/sassoftware/viya4-ark/issues/171

**Comment by kevinlinglesas** [comment]
fyi, @lasiva (lead developer of pre-install report tool) is responding to this issue as it was also referenced in https://github.com/sassoftware/viya4-ark/issues/171

**Comment by lorenzk1213** [comment]
@kevinlinglesas Asking how to make the permissions adequate.

**Comment by thpang** [comment]
Closing this one please refer to the viya4-ark related issue @kevinlinglesas included.
