### ISSUE TITLE
docs: (IAC-1256) Doc for AWS Roles created by IaC is outdated

### ISSUE THREAD

**Issue by canpmh** [sassoftware/viya4-iac-aws#144]
The following doc statement [at this page](https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/CONFIG-VARS.md#iam) appears to no longer be true:

_By default, two custom IAM policies and two custom IAM roles (with instance profiles) are created._

Recent testing shows that the workers_iam_role_name is no longer created at all, and there is no custom policy attached to the cluster_iam_role_name.  Perhaps things changed with the recent upgrade to managed node groups?

The doc page needs to be updated to reflect this change.

In addition, it would be helpful if the doc page could include statements about how/why the AmazonEKSClusterPolicy is leveraged by the cluster iam role.  This role is not used directly by IaC I don't believe, so how/when it is used either by DaC or at runtime by K8s?  Understanding this will help us better navigate conversations with customers who can object to the EC2:CreateTags action on this policy.

**Comment by dhoucgitter** [comment]
We already have an internal Jira ticket open to address this issue, please refer to the Jira IAC-1256 for more details.
