### ISSUE TITLE
Does Viya 2021.1 (LTS) support AWS EBS encryption?

### ISSUE THREAD

**Issue by irchum** [sassoftware/viya4-iac-aws#155]
Hi Team,
I'm part of SAS Technical Support. A customer is asking if Viya 2021.1 (LTS) support AWS EBS encryption.  Can they encrypt the EBS storage using SAS Viya 4 Infrastructure as Code for AWS ?

According to the Viya 2022.1.4 document "Generally, SAS recommends using the native encryption options that are offered by your cloud provider. For example, on AWS, use the AWS-provided encryption for Elastic Block Store (EBS). Cloud providers typically provide disk encryption by default. GlusterFS can be used to encrypt storage for OpenShift."

Encrypted File Systems
https://go.documentation.sas.com/doc/en/itopscdc/v_031/itopssr/n0ampbltwqgkjkn1j3qogztsbbu0.htm#n0per7bwo6dr5dn1eplocoi7xzew

However, this information is missing in  Viya 2021.1 (LTS) document. 

I assume that EBS volumes are encrypted while provisioning resources using IAC when encryption by default is enabled for an AWS region. 
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/EBSEncryption.html#encryption-by-default

Thank you

Ira

**Comment by thpang** [comment]
This is not set by default and would need to be added to the `aws_ebs_volume`. The `encrypted` flag is option and is bey default set to `false`. The resource to update is [here](https://github.com/sassoftware/viya4-iac-aws/blob/7b943a57e2db1cc97a44ba8875c524b8e171fd38/modules/aws_vm/main.tf#L100-L107).

**Comment by dhoucgitter** [comment]
@irchum, have you seen the support for AWS EBS encryption added under PR #183, it was made available in the [5.5.0 - February 17, 2023](https://github.com/sassoftware/viya4-iac-aws/releases/tag/5.5.0) release. Can you take a look and see if that meets your need?

**Comment by dhoucgitter** [comment]
Closing #155 as completed.
