### ISSUE TITLE
SAS Viya 4 is supported on AWS AMI which are CIS Level1 and 2 compliant

### ISSUE THREAD

**Issue by azaadshatru** [sassoftware/viya4-iac-aws#157]
Can you please help in understanding if SAS Viya 4 is supported on AWS AMI which are CIS Level1 and 2 compliant? One of the client in Thailand is asking for the same. By default if we run IaaC scripts for AWS, they provision Amazon Linux AL2 x86_64 which are not CIS compliant it seems. I can see that some CIS compliant AMIs are available in market place [https://aws.amazon.com/marketplace/seller-profile?id=dfa1e6a8-0b7b-4d35-a59c-ce272caee4fc](https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Faws.amazon.com%2Fmarketplace%2Fseller-profile%3Fid%3Ddfa1e6a8-0b7b-4d35-a59c-ce272caee4fc&data=05%7C01%7CShatrughan.Saxena%40sas.com%7Cf05f128a5c7f4ec8c11d08da964c3e97%7Cb1c14d5c362545b3a4309552373a0c2f%7C0%7C0%7C637987551472340817%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=3qWXdapZN0hx7KDq%2BiC1DNo%2FVyyluytRymFTJ5oM0fE%3D&reserved=0) . Can we make use of them to deploy SAS Viya 4?

**Comment by thpang** [comment]
The code base has been tested with the AMI type `AL2_x86_64` You can alter that value in your terraform vars file and test and verify as you see fit. All of the example files have an entry for `cpu_type` that would be the value to update. A big note here, changing this value puts the support component on the customer as this has not been validated by the IAC/DAC team.

If you look [here](https://github.com/sassoftware/viya4-iac-aws/blob/1e1933323df17dbb3bf4e97492c4d7099f896383/docs/CONFIG-VARS.md#additional-node-pools) we have some info and docs linked to show AMI types.

**Comment by azaadshatru** [comment]
I am little confused kinda right now. Can you please help me understand if AL2 AMI is CIS L1/L2 compliant or not? If yes, this means they can use this image in IaaC safely. Other AMI are not tested as given in the link I pasted and that will not get support from SAS.

**Comment by azaadshatru** [comment]
I am talking about this AMI - CIS Amazon Linux 2 Kernel 4.14 Benchmark - Level 1

**Comment by thpang** [comment]
At this time you'd have to test with the AMI. if the customer is in need of this image, the code can be altered, but they are you would be responsible for the general support of the systems created. Which is pretty normal.

**Comment by anapatp** [comment]
We try to change the images following this link.
https://aws.amazon.com/marketplace/seller-profile?id=dfa1e6a8-0b7b-4d35-a59c-ce272caee4fc

But we found the error. Could you suggest?

Resource handler returned message: "[Issue(Code=NodeCreationFailure, Message=Instances failed to join the kubernetes cluster, ResourceIds=[i-078b1654207d94984])] (Service: null, Status Code: 0, Request ID: null)" (RequestToken: e4704f45-99f1-dba2-ce1c-be3cc5b0fbb9, HandlerErrorCode: GeneralServiceException)



Error: error waiting for EKS Node Group (education-eks-amFtEPnZ:node-group-1-20220911150941086500000003) to create: unexpected state 'CREATE_FAILED', wanted target 'ACTIVE'. last error: 1 error occurred:
│       * i-067395e081bf05e21: NodeCreationFailure: Instances failed to join the kubernetes cluster

**Comment by anapatp** [comment]
Currently, we made the custom Amazon images and join the cluster successfully. This image was defined by ami_id. How can we reference ami_id in AWS IaC script?

![image](https://user-images.githubusercontent.com/113654354/190555505-7852c52c-ce7a-49cb-b773-ed103b262af0.png)

**Comment by thpang** [comment]
Hi @anapatp, you'd need to setup a launch_template with a custom AMI type as described [here](https://docs.aws.amazon.com/eks/latest/APIReference/API_Nodegroup.html). Not sure if the new DAC code has the ability to support a custom launch_template, so you'll have to investigate.

**Comment by dhoucgitter** [comment]
Marking as stale/inactive. If there are further questions please open a new [GitHub issue](https://github.com/sassoftware/viya4-iac-aws/issues/new/choose).

**Comment by dhoucgitter** [comment]
Closing #157 as completed.
