### ISSUE TITLE
Request to support remote state storage

### ISSUE THREAD

**Issue by manoatsas** [sassoftware/viya4-iac-aws#161]
Currently, terraform state file is written to local disk. This state file contains some sensitive information in plain text.

Please add support for remote backend storage for terraform state files - https://www.terraform.io/language/state/remote, that support encryption.

**Comment by sayeun** [comment]
I can see how this could be useful, but after requirement discussion with PM, we don't have plans to add this support at this time. If demand changes in the future, it would need to go through Feature Request process.
