### ISSUE TITLE
Terraform throws errors on subsequent deployments.

### ISSUE THREAD

**Issue by tclehman** [sassoftware/viya4-iac-aws#167]
### Terraform Version Details

I am getting errors when re-deploying to the same AWS subaccount and region. Screenshot of errors attached. I have deleted everything that I can find in the account that this originally deployed to. I have deleted the tfstate backup file in the application deployment.

Terraform Version Details:
{
  "terraform_version": "\"1.1.7\"",
  "terraform_revision": "null",
  "terraform_outdated": "true",
  "provider_selections": "{}"
}
![Terraform_error](https://user-images.githubusercontent.com/49881073/196261632-43e5a0c0-ebda-4536-bfff-4473ace8bad8.png)

```
### Terraform Variable File Details

# !NOTE! - These are only a subset of the variables in CONFIG-VARS.md provided
# as examples. Customize this file to add any variables from CONFIG-VARS.md whose
# default values you want to change.



# ****************  REQUIRED VARIABLES  ****************
# These required variables' values MUST be provided by the User
prefix                                  = "viya4aws"
location                                = "us-east-2" # e.g., "us-east-1"
# ****************  REQUIRED VARIABLES  ****************



# !NOTE! - Without specifying your CIDR block access rules, ingress traffic
#          to your cluster will be blocked by default.



# **************  RECOMMENDED  VARIABLES  ***************
default_public_access_cidrs = ["70.244.47.179/32"]  # e.g., ["123.45.6.89/32"]
ssh_public_key              = "~/.ssh/id_rsa.pub"
# **************  RECOMMENDED  VARIABLES  ***************



# Tags for all tagable items in your cluster.
#tags                                    = { } # e.g., { "key1" = "value1", "key2" = "value2" }



# Postgres config - By having this entry a database server is created. If you do not
#                   need an external database server remove the 'postgres_servers'
#                   block below.
#postgres_servers = {
#  default = {},
#}



## Cluster config
kubernetes_version                      = "1.21"
default_nodepool_node_count             = 2
default_nodepool_vm_type                = "m5.2xlarge"
default_nodepool_custom_data            = ""



## General
efs_performance_mode                    = "maxIO"
storage_type                            = "standard"



## Cluster Node Pools config
node_pools = {
  cas = {
    "vm_type" = "m5.2xlarge"
    "cpu_type"     = "AL2_x86_64"
    "os_disk_type" = "gp2"
    "os_disk_size" = 200
    "os_disk_iops" = 0
    "min_nodes" = 1
    "max_nodes" = 5
    "node_taints" = ["workload.sas.com/class=cas:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class" = "cas"
    }
    "custom_data" = ""
    "metadata_http_endpoint"               = "enabled"
    "metadata_http_tokens"                 = "required"
    "metadata_http_put_response_hop_limit" = 1
  },
  compute = {
    "vm_type" = "m5.8xlarge"
    "cpu_type"     = "AL2_x86_64"
    "os_disk_type" = "gp2"
    "os_disk_size" = 200
    "os_disk_iops" = 0
    "min_nodes" = 1
    "max_nodes" = 5
    "node_taints" = ["workload.sas.com/class=compute:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class"        = "compute"
      "launcher.sas.com/prepullImage" = "sas-programming-environment"
    }
    "custom_data" = ""
    "metadata_http_endpoint"               = "enabled"
    "metadata_http_tokens"                 = "required"
    "metadata_http_put_response_hop_limit" = 1
  },
  stateless = {
    "vm_type" = "m5.4xlarge"
    "cpu_type"     = "AL2_x86_64"
    "os_disk_type" = "gp2"
    "os_disk_size" = 200
    "os_disk_iops" = 0
    "min_nodes" = 1
    "max_nodes" = 5
    "node_taints" = ["workload.sas.com/class=stateless:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class" = "stateless"
    }
    "custom_data" = ""
    "metadata_http_endpoint"               = "enabled"
    "metadata_http_tokens"                 = "required"
    "metadata_http_put_response_hop_limit" = 1
  },
  stateful = {
    "vm_type" = "m5.4xlarge"
    "cpu_type"     = "AL2_x86_64"
    "os_disk_type" = "gp2"
    "os_disk_size" = 200
    "os_disk_iops" = 0
    "min_nodes" = 1
    "max_nodes" = 3
    "node_taints" = ["workload.sas.com/class=stateful:NoSchedule"]
    "node_labels" = {
      "workload.sas.com/class" = "stateful"
    }
    "custom_data" = ""
    "metadata_http_endpoint"               = "enabled"
    "metadata_http_tokens"                 = "required"
    "metadata_http_put_response_hop_limit" = 1
  }
}



# Jump Server
create_jump_vm                        = true
create_nfs_public_ip = false
```

### Steps to Reproduce

To reproduce this, all I had to do was:
1) Use terraform to deploy (successfully)
2) Use terraform to delete (successfully)
3) Run the same terraform deploy command.

These errors have occurred ever since the first initial and successful deployment. 

### Expected Behavior

It should deploy/destroy successfully with no errors each and every time it's run.

### Actual Behavior

On the second deployment, it will throw 3 errors.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by thpang** [comment]
Is the kubeconfig file the code is access the correct cluster? The endpoint the code is trying to access for the cluster in your code above is:

![image](https://user-images.githubusercontent.com/32514746/196263220-b2a711f2-f699-436f-a924-6e38e4903121.png)

**Comment by tclehman** [comment]
I can verify that the endpoint listed each time we attempt to deploy is matching what is shown in AWS. It is getting regenerated with a new prefix of characters each time. I have destroyed and redeployed since my last update, and I get the same error, with a different endpoint URL. That URL does match what AWS shows in the console as the API server endpoint.

**Comment by Technolero** [comment]
In terraform.tfvars, is the value for default_public_access_cidrs the public IP of the machine you are deploying from?

**Comment by tclehman** [comment]
Yes, it is. My public IP is currently "70.244.47.179" and that is what I've put into the default_public_access_cidrs parameter.

**Comment by tclehman** [comment]
I didn't mean to imply that the actual parameter is 70.244.47.179 without the cidr range at the end. If you look at the screenshot in my original post, it includes the "/32" in the parameter value exactly as you have shown.

**Comment by thpang** [comment]
Ok, so the timeout is saying that from whatever machine you're running tf that it cannot access that endpoint for the cluster. I would try from that box setting KUBECONFIG to the kubernetes config file and running `kubectl get node -o wide` to see if you can access the cluster from that machine

**Comment by Technolero** [comment]
@tclehman I have seen the three errors before during some testing. I was deploying from a bastion server in AWS when it occurred. I was able to work around the issue by adding the -eks_worker_sg security group to the bastion server, then rerunning the terraform apply. I know it doesn't solve the mystery, but it allows the infrastructure to build successfully (for me anyway) and the cluster has worked as I expect ever since.

**Comment by tclehman** [comment]
@Technolero 
I went in and checked the bastion host (on my deployment its called the jump-vm, I assume these are the same thing) and it seems to already have that security group attached to it. Please see attached screenshot.

![Capture](https://user-images.githubusercontent.com/49881073/196525784-905d2f2f-2bb2-40c0-83dc-7d408d8e2a7d.PNG)


@thpang  I am trying to capture the output but am unfortunately lacking in expertise here. I believe I need to be inside the cluster to get that kubectl command working, correct? I was having trouble getting the command to work. See screenshot below.

![Capture2](https://user-images.githubusercontent.com/49881073/196526249-3156897b-2454-46fc-a902-6992b5201ff2.PNG)

**Comment by tclehman** [comment]
@Technolero I misunderstood before, makes sense.

I ran ifconfig on the terraform host that I am running the deployment from. For your reference, here is the output:

![image](https://user-images.githubusercontent.com/49881073/196529591-f3724b06-2b5c-4aac-b8ac-d51fe4904897.png)




Then I added those IP's to the eks_worker_sg:

![image](https://user-images.githubusercontent.com/49881073/196529873-9ccea997-e546-4737-ac8a-4ba4e50dfd55.png)



I then reran the deployment, but unfortunately still get the same errors:

![image](https://user-images.githubusercontent.com/49881073/196530151-02c5cdbf-b5be-48b4-b417-dda54193be67.png)

**Comment by tclehman** [comment]
@Technolero 
As an additional test, I opened up all traffic on that security group. I still got the error on deployment:

![image](https://user-images.githubusercontent.com/49881073/196532880-2277f494-5ab3-49f4-8591-bf2379ff89dc.png)

**Comment by thpang** [comment]
From the 172.17.0.1/32 machine were you able to run the `kubectl` command and look at your cluster?

**Comment by tclehman** [comment]
Kubectl has been installed on the docker image, and not the host machine. With that in mind, it appears I am only able to run it from with the container. Would you know how I would be able to exec into the container to run the commands you are suggesting.

**Comment by tclehman** [comment]
@Technolero  @thpang 
I suspect the issue is due to network accessibility of the terraform host itself. Would it be ok if I added a public ALB in front of the terraform host, and pointed the default_public_access_cidr to that load balancer?

**Comment by Technolero** [comment]
@tclehman when you did the ifconfig, that returned your private IPs, which were not what connects to the API endpoint, your public IP is. Not sure about your AWS VPC architecture, but either your terraform host has a public IP assigned to it or the NAT gateway in your VPC has one, and those are the public IPs that need to be added to the worker security group. You previously mentioned a 70.244.47.179 IP, what resource is that associated with?

**Comment by dhoucgitter** [comment]
@tclehman, were you able to resolve the load balancer issue that you were having?

**Comment by tclehman** [comment]
I think so. It's been over a year I don't recall what this issue even was for.

**Comment by dhoucgitter** [comment]
Thanks, closing #167 as resolved.
