### ISSUE TITLE
Feature Request : Spot instances for AWS k8 worker nodes

### ISSUE THREAD

**Issue by sandeepksaini** [sassoftware/viya4-iac-aws#190]
Can we have a feature where we can use AWS spot instances for k8 worker nodes?

**Comment by biohazd** [comment]
Allowing a mix of Spot and Normal instances would also be great.

**Comment by biohazd** [comment]
I am building a few DEV clusters and the resouce required are pretty high to run the pods.  So using SPOT instances on AWS would help keep costs down.

**Comment by dhoucgitter** [comment]
At this time SAS does not support spot VM's. If this becomes a requirement in the future we'll revisit this issue.
