### ISSUE TITLE
Feature request : arm64

### ISSUE THREAD

**Issue by jonathanmassehsj** [sassoftware/viya4-iac-aws#191]
### Terraform Version Details

I tried to run SAS on the new Graviton 3 CPU (r7g instance on AWS) but it's not compatible with arm64. 

We have R Studio with Graviton since 2 years and we don't have any issue.

Is there a plan to have arm64 on SAS Viya? Or is there a way to have Graviton CPU to run SAS Viya?

Many thanks for your help,

### Steps to Reproduce

Try to install and run SAS Viya container on a arm64 CPU.

### Expected Behavior

To have SAS Viya running on a Graviton CPU.

### Actual Behavior

Doesn't work, doesn't support arm64.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Viya2023** [comment]
Are there any good news about SAS Viya Graviton/ARM64-support?
If not, is it planned to be supported?
