### ISSUE TITLE
Subnet usage by IAC on AWS

### ISSUE THREAD

**Issue by sukrws** [sassoftware/viya4-iac-aws#216]
Hi Guys
I cant find any details about what gets put into what subnet on an AWS deployment.
I understand what goes in Public and Private but what is database for?
The only thing I found was for Azure where its said that Netapps storage would go there if HA was chosen So is it a storage subnet?

**Comment by dhoucgitter** [comment]
Hi @sukrws, the upcoming release will include changes to the subnet composition that IaC for AWS creates for you as well as the pre-existing subnet requirements used in bring your own network configurations. You can check out the relevant documentation prior to it becoming generally available in PR #242. 
Regarding the database subnets, they can be used for the resources required by the RDS server if one is configured if you'd like to isolate the RDS server resources from the public subnets. If you only provide public subnets and configure an RDS server, the public subnets will be used instead. Regardless of which subnets are used for RDS, two subnets in different availability zones are required to support redundancy in the event that a failure occurs in one AZ.

**Comment by dhoucgitter** [comment]
@sukrws, the latest release [8.0.0 - December 6, 2023](https://github.com/sassoftware/viya4-iac-aws/releases/tag/8.0.0) provides additional details surrounding the [Subnet Requirements](https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/CONFIG-VARS.md#subnet-requirements) for [BYO networking scenarios](https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/user/BYOnetwork.md#supported-scenarios-and-requirements-for-using-existing-network-resources) as well as non-BYO network scenarios. If you are looking for additional information not covered in the documentation you can re-open this issue or create a new one with your question, thanks.
