### ISSUE TITLE
Feature: (IAC-1272) add a route53 dns entry

### ISSUE THREAD

**Issue by biohazd** [sassoftware/viya4-iac-aws#219]
Allow creation of a route53 dns entry that will point to the ingress loadbalncer that was created.

this is so we can use a simple domain name to access the load balancer

**Comment by dhoucgitter** [comment]
Discussed this issue with IAC PM and the IAC team. The decision was made to close this feature request as will not do at this point in time. Setting up a route53 DNS entry manually for use with Viya deployed by the viya4-iac-aws IAC and viya4-deployment DAC projects is an alternative.
