### ISSUE TITLE
Does this project support AWS Site to Site (Direct Connect)?

### ISSUE THREAD

**Issue by miaeyg** [sassoftware/viya4-iac-aws#251]
Hi,

Wondering if this project supports setting up a K8S cluster on AWS with Direct Connect (site to site VPN)? If so, is there anything special to note about this configuration that needs to be adapted in the "terraform.tfvars" file?

Thanks!

**Comment by dhoucgitter** [comment]
Hi @miaeyg, viya4-iac-aws focuses on provisioning the AWS cloud infrastructure resources that are required to deploy SAS Viya platform product offerings. Use of AWS Direct Connect (site to site VPN) to provide access to AWS resources is not within the scope of this project.

**Comment by miaeyg** [comment]
Hi @dhoucgitter 

Wait, before you close this issue - I think you did not understand my question... my question is about a pre-existing AWS instance that is configured with Site to Site VPN and I want to setup a Viya cluster on it. I am not expecting the project to configure the Site to Site VPN but asking if any of the project's config variables require special attention in this case.

**Comment by dhoucgitter** [comment]
Hi @miaeyg, are you trying to run viya4-iac-aws from a pre-existing AWS instance in order to create your EKS cluster? If you are an admin for that AWS instance you should be able to install any requirements on that instance and run IaC from there just as you would do from an AWS instance that you SSH'd into from your development network. Is the pre-existing AWS instance part of a bring your own network scenario deployment that you have planned? If so, take a look at https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/user/BYOnetwork.md to understand the configuration requirements depending on your scenario.

**Comment by miaeyg** [comment]
Hi @dhoucgitter 

At https://github.com/sassoftware/viya4-iac-aws/blob/faf3f0ebcc46cb4287fac70caac6733033d2e8b5/docs/CONFIG-VARS.md#admin-access it says:

_NOTE: When deploying infrastructure into a private network (e.g. a VPN), with no public endpoints, the options documented in this block are not applicable._

Q1: Does "private network" include AWS Site to Site VPN? 
Q2: What the meaning of "not applicable" does it mean that the options need to be kept empty or deleted or can be with a value and they will be ignored? Also what options specifically are "not applicable" - it is not mentioned.

**Comment by dhoucgitter** [comment]
Hi @miaeyg, added my responses below.
> Q1: Does "private network" include AWS Site to Site VPN?
> Q2: What the meaning of "not applicable" does it mean that the options need to be kept empty or deleted or can be with a value and they will be ignored? Also what options specifically are "not applicable" - it is not mentioned.

R1: If you are using a VPN to access EC2 instances in your AWS VPC, it's likely that you are accessing a "private network" or one that does not have a public IP address.

R2: When deploying infrastructure into a private network with no public endpoints, the four `*_public_access_cidrs` configuration variables intended to convey the public IP CIDRs that should be allowed access to your cluster's resources are not so relevant. "Not applicable" in this case means that you could leave all four `*_public_access_cidrs` variables undefined or set default_public_access_cidrs to [], the empty list, and instead use the `*_private_access_cidrs` configuration variables to convey which EC2 CIDR ranges you wish to provide access to your cluster resources from. If you created a bastion or IaC client VM in your VPC that you are accessing via your site to site VPN, you could set `default_private_access_cidrs` to the CIDR range for that VMs private IP address as a starting point. For example, if your IaC client VMs private address is 10.1.0.1, you could set `default_private_access_cidrs = ["10.1.0.1/32"]`. If you plan on accessing cluster resources or the application ingress from other private IP addresses in your VPC, you could specify a broader CIDR range that includes them or add additional CIDR ranges to the list for the `*_private_access_cidrs` variables that you are using.

**Comment by miaeyg** [comment]
Hi @dhoucgitter 

So if I remove the four *_public_access_cidrs configuration variables and also use an internal PostgreSQL server then IaC will _not_ auto-create any public subnets?

**Comment by dhoucgitter** [comment]
Hi @miaeyg, setting or not setting any of the four `*_public_access_cidrs` variables and using an internal PostresSQL server will not affect whether IaC will create public subnets, or the other subnets IaC creates for you. Unless you pre-create the required subnets and then supply the subnet ids for those existing subnets in the `subnet_ids` IaC configuration variable, IaC will create the required subnets for you. Read through the [Subnet Requirements](https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/CONFIG-VARS.md#subnet-requirements) section which should help explain which subnets are created if you are not supplying your own via the `subnet_ids` variable. Providing your own subnet ids qualifies as a [BYO networking scenario](https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/user/BYOnetwork.md#supported-scenarios-and-requirements-for-using-existing-network-resources). Pay particular attention to the `Required Variables`, `Optional Variables` and `Additional Requirements` columns in the table should you choose to go with a BYO networking scenario.

**Comment by miaeyg** [comment]
Hi @dhoucgitter, one last question about this...is it OK to set (different) values for _both_ default_private_access_cidrs and default_public_access_cidrs in the same terraform.tfvars file?

**Comment by dhoucgitter** [comment]
Hi @miaeyg, you should be able to set different values for those variables but I'd be curious about why you are trying to both of them. `default_private_access_cidrs` would be used if you are deploying infrastructure into a private network with no public endpoints. See [Admin Access ](https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/CONFIG-VARS.md#admin-access) for guidance. If you are configuring public endpoints for your cluster, you could set `default_public_access_cidrs` to enable access from your chosen set of CIDR ranges instead.
