### ISSUE TITLE
Why is the eks-default VM running on the private subnet and not on the control-plane subnet?

### ISSUE THREAD

**Issue by miaeyg** [sassoftware/viya4-iac-aws#260]
Using the current version of this project I see that the VM named "sas-eks-default" ("sas" is the cluster name) is running in subnet "sas-private-<region>" which is a surprise as I thought the eks-default machines should run on the "control-plane" subnets and not on the "private" subnets.
Is this a bug or my understanding is incorrect about placement of VMs on subnets?

**Comment by dhoucgitter** [comment]
@miaeyg, none of the worker nodes are expected to be placed in either of the two control-plane subnets. The single private subnet, which is located in a single AZ, is the subnet that all worker node IPs should be allocated from. Your "sas-eks-default" VM is running in the private subnet as expected.

**Comment by miaeyg** [comment]
Hi @dhoucgitter, I have 4 "sas-eks-generic" instances + 1 "sas-eks-cas" instance + 1 "sas-eks-default" instance
_All_ of them are running on the single "private" subnet.

I do not understand what is supposed to run on the "control-plane" subnets...
