### ISSUE TITLE
Why is the number of launch templates double the number of managed node groups?

### ISSUE THREAD

**Issue by miaeyg** [sassoftware/viya4-iac-aws#263]
Using the latest version of this project, I ran the script and looked at AWS Management Console EC2->Auto Scaling Groups and I see three autoscaling groups: default, cas and generic each with its own associated launch template (named eks-<randomstring>) so a total of 3 launch templates.

However, if I go to EC2->Launch Templates, I see 6 launch templates: the same 3 as described above + 3 additional ones named <prefix>-eks-default-lt-<randomstring>,  <prefix>-eks-generic-lt-<randomstring> and <prefix>-eks-cas-lt-<randomstring>

Q1: What is the purpose of the three additional launch templates? Are they used anywhere?

Q2: (more of a generic AWS question but related to launch templates) I created a new launch template version (version 2) of the launch template associated with the CAS auto scaling group in which I associated the new version with a Placement Group that I manually created. I set version 2 as the default template version. I reduced the CAS managed group desired count to 0 and then set it to 1 but to my surprise the new CAS instance did NOT have the placement group associated with it - any idea why?

**Comment by dhoucgitter** [comment]
Hi @miaeyg, not sure why you are seeing 6 launch templates instead of the expected 3 but I will see if I can recreate that and follow up. Not sure about the behavior you noticed for Q2 since our placement group support is still planned. It does sound like the existing CAS managed node group does not know about your new launch template.

**Comment by dhoucgitter** [comment]
Hi @miaeyg, I created a cluster with four node_pools defined in my terraform-input.vars file: cas, compute, stateful and stateless. Checking EC2->Auto Scaling Groups in the console I see 5 total auto scaling groups one scaling group for each of the four node pools defined in tfvars plus the expected default scaling group for the default node_pool. The name of the stateless auto scaling group is eks-stateful-20240122142539075700000037-32c698c8-03c1-41e2-8b4a-ea0093d319aa. There is a separate launch template/configuration for each auto scaling group. Could you try creating a new cluster in a new region where you have verified that you have zero auto scaling groups present and see if you still get double the expected scaling groups? If you do, could you share a sanitized terraform-input.vars file so I can give it a try? Thanks.

**Comment by miaeyg** [comment]
Hi @dhoucgitter , how many templates do you see at EC2->Launch Templates ?

Here is what I see in EC2 -> Launch Templates:

<img width="818" alt="image" src="https://github.com/sassoftware/viya4-iac-aws/assets/52774627/cd05fd1e-9391-4c81-bfe2-fc621e9bdc37">

And here is what I see at EC2 -> Auto Scaling Groups:

<img width="816" alt="image" src="https://github.com/sassoftware/viya4-iac-aws/assets/52774627/6abc2431-16e9-42d6-804c-154345674854">

Is this OK?

**Comment by dhoucgitter** [comment]
Hi @miaeyg. Yes, the number of launch templates looks OK for your configuration. IaC creates a launch template for each managed node group that exists. The launch template for a managed node group in Amazon EKS is used to define the configuration for the EC2 instances in that node group. When a new node needs to be launched, such as during initial node group creation, EKS will refer to the launch template to determine how to launch the instance. When auto scaling is enabled, a separate launch template also gets created for each auto scaling group. The launch template for an Auto Scaling group is used to define the configuration for the EC2 instances that will be launched and managed by that Auto Scaling group. I can confirm with five managed node_groups and autoscaling enabled (which is true by default) that a total of ten (two sets of five) launch templates are present with the same naming conventions that you noted above.

**Comment by miaeyg** [comment]
Hi @dhoucgitter , not sure I understood why the number of templates is doubled but if you say this is fine then I will close this issue. Thanks!
