### ISSUE TITLE
Does this project support AWS PrivateLink?

### ISSUE THREAD

**Issue by miaeyg** [sassoftware/viya4-iac-aws#268]
Does this project support setting up a PrivateLink for cases in which public access is not allowed?
https://docs.aws.amazon.com/vpc/latest/privatelink/what-is-privatelink.html

**Comment by miaeyg** [comment]
I think the answer is "yes" as I found that VPC endpoints are created for some AWS services including "ecr". Would be nice to get a confirmation :)

Just for my understanding - if I used this project to create a public subnet + NAT gateway (default configuration) then theoretically these VPC endpoints are not required because there is public Internet access via the NAT gateway and so I can access the public AWS services even from the private subnet, right?

**Comment by dhoucgitter** [comment]
Hi @miaeyg, your understanding is correct. VPC endpoints provide an alternative to access necessary AWS services when there is no public Internet access which could be true for clusters configured without a NAT gateway. For customers that want to manage vpc_endpoints themselves or to prevent IaC from creating them, you can utilize the `vpc_private_endpoints_enabled` variable, see the CONFIG-VARS.md [entry](https://github.com/sassoftware/viya4-iac-aws/blob/main/docs/CONFIG-VARS.md#vpc-endpoints).
