### ISSUE TITLE
harden nfs security

### ISSUE THREAD

**Issue by enderm** [sassoftware/viya4-iac-aws#29]
the nfs security group currently opens a ports between the nfs server and all hosts that use the  "sg" security group (i.e. the jump host and the aks nodes). 
NFS uses mostly port 111 and 2049, but may also use dynamic ports for mountd, statd, rquotad, lockd.
We want to configure nfs so that these service use static ports, and then change the security group to open only those ports.
Reference: https://tldp.org/HOWTO/NFS-HOWTO/security.html

**Comment by thpang** [comment]
Was this one address with #27 ? Checking as that code has been merged. If it has been addressed close this issue. Thx.

**Comment by enderm** [comment]
#27 did not address this. The current item was opened with the understanding that #27 provided the basic nfs functionality while leaving some hardening work for a later time.

**Comment by dhoucgitter** [comment]
Requires PM review.
