### ISSUE TITLE
S3 endpoint still is of type Gateway and not Interface

### ISSUE THREAD

**Issue by miaeyg** [sassoftware/viya4-iac-aws#306]
### Terraform Version Details

Not relevant

### Terraform Variable File Details

modules/aws_vpc/variables.tf

### Steps to Reproduce

Version 8.4.0 release notes at https://github.com/sassoftware/viya4-iac-aws/releases/tag/8.4.0 it says `private endpoint type for S3 should be of type Interface` but the `main` branch even in version 8.5.1 still uses S3 endpoint of type Gateway.

When cloning the project with the latest version 8.5.1 it seems like this patch did not make it through to the main branch even though it was documented in the official 8.4.0 release

### Expected Behavior

S3 endpoint should be of type Interface like all other VPC endpoints

### Actual Behavior

S3 endpoint is still of type Gateway 

### References

https://github.com/sassoftware/viya4-iac-aws/releases/tag/8.4.0

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by miaeyg** [comment]
To be more specific see this line: https://github.com/sassoftware/viya4-iac-aws/blob/main/modules/aws_vpc/variables.tf#L129

**Comment by dhoucgitter** [comment]
@miaeyg, thanks for opening this issue and bringing it to our attention. See the linked PR and look for an update in the upcoming release that addresses it.

**Comment by dhoucgitter** [comment]
https://github.com/sassoftware/viya4-iac-aws/pull/307 is a part of the latest release https://github.com/sassoftware/viya4-iac-aws/releases/tag/8.6.0 that contains a fix for this issue.
