### ISSUE TITLE
Support bring your own network resources

### ISSUE THREAD

**Issue by manoatsas** [sassoftware/viya4-iac-aws#54]
- VPC id
- Subnet ids
- Security Group

**Comment by gnan-s** [comment]
Hello 
This is good news that you are supporting to bring in our own VPC, subnets. We also have restrictions in creating new IAM roles and Policies, and using existing AMI ids for jump/nfs VMs when we create this cluster. Would you be able to include support to bring our own IAM roles/policies and AMI ids (for NFS and Jump)  in this script. Thanks

**Comment by thpang** [comment]
@gnan-s , one can bring their own IAM policy as long as it contains the items listed [here](https://github.com/sassoftware/viya4-iac-aws/blob/main/files/policies/devops-iac-eks-policy.json). The code does currently add a policy for EBS CSI drivers on the EKS worker nodes that is required. If that's not allowed, then at this time we do not support bring your own IAM. Currently the jump/nfs vm's are controlled and we don't allow folks to change that. These are Ubuntu images. We have cloud-init scripts written for these images that add the needed software to stand up a viable eco-system for SAS Viya 4 consistently every time.  You can open separate issue and we can investigate. Create an issue for each item don't stack requirements into a single issue.
