### ISSUE TITLE
non-default port number for external postgres not being honored on inbound rule for security group

### ISSUE THREAD

**Issue by hahewlet** [sassoftware/viya4-iac-aws#59]
Deployed from main on 11May2021. The terraform.tfvars used is attached, [terraform.txt](https://github.com/sassoftware/viya4-iac-aws/files/6466584/terraform.txt). Of note are the following postgres variables.

create_postgres                       = true # set this to "false" when using internal Crunchy Postgres and AWS Postgres is NOT needed
postgres_storage_encrypted = true
postgres_server_version = "12"
postgres_multi_az = true
postgres_server_port = 5452

The postgres server itself is running on port 5452 as expected. However the postgres inbound rule lists the default port number of 5453 instead of 5452. 

![image](https://user-images.githubusercontent.com/44618553/117986392-92903780-b307-11eb-9312-ebee23884026.png)

I will have the env around for a brief time. If there are any terraform state commends you'd like run for further info, please let me know.

**Comment by thpang** [comment]
This has not been implemented and surfaced to the end user at this time. This may be in the future. Will be reaching out to the IAC to discus.

**Comment by hahewlet** [comment]
The README.md file points the customer to variables.tf multiple times. which is what drove me to took in this file for options. 

Customize Input Values
Create a file named terraform.tfvars to customize any input variable value. For starters, you can copy one of the provided sample variable definition files in examples folder. For more details on the variables declared in variables.tf refer to CONFIG-VARS.md.

NOTE: You will need to update the cidr_blocks in the variables.tf file to allow traffic from your current network. Without these rules, access to the cluster will only be allowed via the AWS Console.

When using a variable definition file other than terraform.tfvars, see Advanced Terraform Usage for additional command options.

**Comment by thpang** [comment]
The reference to the variables.tf file has been removed from the README.md file. Users are now pointed to the CONFIG-VARS.md file for reference.

Keeping this one open; however, in keeping with the spirit of these repos and keeping the functionality in parity as much as possible, at the current time, neither Azure or GCP allow one to alter that port. 

Knowing this information, this issue may be closed and the variable removed to eliminate confusion.

**Comment by hahewlet** [comment]
That is reasonable, unless/until we have a customer request for this feature.

**Comment by thpang** [comment]
Closing this one for now. If we have a way to expose this with the other providers in the future, we'll open a new issue.
