### ISSUE TITLE
Add managed nodepools as an option

### ISSUE THREAD

**Issue by alessiotoma** [sassoftware/viya4-iac-aws#73]
EKS nodepools can be now be tainted in the latest version of the Terraform AWS module ( see https://github.com/terraform-aws-modules/terraform-aws-eks/issues/1403 ). On that basis, is there anything that is preventing us from moving from self-managed nodepools to managed nodepools ? This would make the EKS update process easier.

**Comment by thpang** [comment]
We've started looking into this one. As we find out information we'll provide feedback. There will also be a PR with the code changes addressing this issue.

**Comment by egoienola** [comment]
Has this been implemented now? It certainly looks as though the commit call https://github.com/sassoftware/viya4-iac-aws/commit/d66d5b9205ca57a4b38149a4a420a0f4fa8dde8b introduced key changes necessary to switch to the managed node groups (commit message seems to confirm this). The following output also suggests that to be the case:
`module.eks.module.eks_managed_node_group["cas"].aws_eks_node_group.this[0]: Still creating... [3m30s elapsed]
module.eks.module.eks_managed_node_group["stateless"].aws_eks_node_group.this[0]: Still creating... [3m30s elapsed]
module.eks.module.eks_managed_node_group["compute"].aws_eks_node_group.this[0]: Still creating... [3m30s elapsed]
module.eks.module.eks_managed_node_group["default"].aws_eks_node_group.this[0]: Still creating... [3m30s elapsed]
`
Is there anything else pending to complete this request?

**Comment by dhoucgitter** [comment]
@egoienola, support for EKS managed node groups was added under PR #122 and was made available starting with release https://github.com/sassoftware/viya4-iac-aws/releases/tag/5.0.0

**Comment by dhoucgitter** [comment]
Closing #73 as Done.
