### ISSUE TITLE
id_rsa not created by terraform

### ISSUE THREAD

**Issue by StefanGiuros** [sassoftware/viya4-iac-aws#83]
Steps:

- using a CentOS WSL machine, be it **host 1**
- deployed prerequisites
- created ssh keys
- cloned project
- updated `terraform.tfvars` 

Once cluster was deployed, without errors, i was able to login into **jump** host from **host 1**
````
 ssh jumpuser@<jumphost_public_DNS>
````

However, SSH from **jump** host to **NFS server** does not work:
````
ssh nfsuser@<NFS_server_private_DNS>
nfsuser@i[..]: Permission denied (publickey).
````

I have noticed that  on **jump** host, in `/home/jumpuser/.ssh` there is no `id_rsa` key file created.
I presumed the the viya4-iac-aws tool creates a new `id_rsa` SSH keypair in  `jumpuser`'s `.ssh` directory, and places that key in **nfs-server.**

Thanks

**Comment by thpang** [comment]
You are correct the terraform code base does not create the ssh keys. You have to supply those. You do supply the public key in the `terraform.tfvars` file. It looks like this:

```terraform
ssh_public_key                          = "~/.ssh/id_rsa.pub"
```
The host machine has the private key. If you do need access to the NFS server there are 2 ways you can go about this. I've listed both below.

## Sharing your private key on the Jump server to access your NFS server

If you don't need public access to your NFS server, but would like to access the box, you can from your Jump server. Here are the steps:

1. Copy the contents of the private key associated with the `ssh_public_key = "~/.ssh/id_rsa.pub"` entry in your `terraform.tfvars` file to your clipboard.
2. Logon to your Jump server.
3. Edit the file `~/.ssh/id_rsa`
4. Paste in the contents you copied in step 1 from your clipboard into the file
5. Save the file
6. Change the permissions of the file: `chmod 400 ~/.ssh/id_rsa`
7. Now ssh into your jump box.

What you've done here is provide the private key to match the public key that the NFS server has so you'll now have access.

## Turning on public access to your NFS server

If you do want pubic access to your NFS server, you can change this with the following entry in the `terraform.tfvars` file.

The files by default have this value:

```terraform
create_nfs_public_ip                  = false
```

If you need access from your system you can change this value to `true`

```terraform
create_nfs_public_ip                  = true
```

Let us know if you have any other questions.
