### ISSUE TITLE
BYONetwork issues: aws_vpc.vpc is empty tuple

### ISSUE THREAD

**Issue by shealym** [sassoftware/viya4-iac-aws#90]
### Issue

Greetings,

Attempting to BYONetwork, I'm running into issues trying Scenario 1 here: 

https://github.com/sassoftware/viya4-iac-aws/blob/byo_sg/docs/user/BYOnetwork.md

Thanks for the help!

Michael

### Terraform Version

From the Dockerfile:
```
ARG TERRAFORM_VERSION=1.0.0
ARG AWS_CLI_VERSION=2.1.29
FROM hashicorp/terraform:$TERRAFORM_VERSION as terraform

FROM amazon/aws-cli:$AWS_CLI_VERSION
ARG KUBECTL_VERSION=1.19.9
```

### Terraform Variable File

```
vpc_id = "vpc-08f421a66d51167c7"
subnets = {
    "private" : ["172.16.0.0/18", "172.16.64.0/18"],
    "public" : ["172.16.129.0/25", "172.16.129.128/25"],
    "database" : ["172.16.128.0/25", "172.16.128.128/25"]
}
```

### Steps to Reproduce

Create a 172.16.0.0/16 vpc, and enable DNS hostnames and resolution
```
git clone https://github.com/sassoftware/viya4-iac-aws
cd viya4-iac-aws
docker build -t viya4-iac-aws .
cp examples/sample-input-minimal.tfvars ./terraform.tfvars
```
Update prefix, location, and add a mandatory tag in ./terraform.tfvars
Add the existing /16 vpn_id and valid subnet ranges to ./terraform.tfvars
```
docker run --rm --group-add root \
  --user "$(id -u):$(id -g)" \
  --env-file=$HOME/.aws_docker_creds.env \
  --volume=$HOME/.ssh:/.ssh \
  --volume=$(pwd):/workspace \
  viya4-iac-aws \
  plan -var-file=/workspace/terraform.tfvars \
       -state=/workspace/terraform.tfstate

```
### Expected Behavior

Generate a standard deployment plan

### Actual Behavior

This error 8 times:

```
╷
│ Error: Invalid index
│
│   on modules/aws_vpc/main.tf line 39, in resource "aws_vpc_endpoint" "private_endpoints":
│   39:   vpc_id             = aws_vpc.vpc.0.id
│     ├────────────────
│     │ aws_vpc.vpc is empty tuple
│
│ The given key does not identify an element in this collection value.
╵

```

### Additional Context

Changing line 39 of modules/aws_vpc/main.tf from:
```
vpc_id             = aws_vpc.vpc.0.id
```
to:
```
vpc_id             = local.vpc_id
```
...and rebuilding the container seems to resolve the issue for Scenario 1 (and seems to pass regression when no vpc_id is referenced as well)...but I haven't validated every scenario on this page to know if that's really the correct fix:  

https://github.com/sassoftware/viya4-iac-aws/blob/byo_sg/docs/user/BYOnetwork.md

**Comment by enderm** [comment]
I believe this would be fixed as as part of https://github.com/sassoftware/viya4-iac-aws/pull/86, in particular  https://github.com/sassoftware/viya4-iac-aws/pull/86/files#diff-8228cfb856c202d0817961237550571e52a8aae20567cb6177a1ea356b7acd55

**Comment by shealym** [comment]
Ah, ok...I'll wait for that commit and then recheck.  Thanks Matthias!
