### ISSUE TITLE
SSH Access to EKS Nodes

### ISSUE THREAD

**Issue by shealym** [sassoftware/viya4-iac-aws#92]
Greetings,

Could viya4-iac-aws be updated to put the jump-server ssh key on the EKS nodes, to match the functionality of the aks_cluster_ssh_public_key setting on viya4-iac-azure?  It's very helpful to have access to the underlying nodes for a number of different admin/tshooting tasks.

Seems like an easy way to do that would be to add:

```
key_name                             = "${var.prefix}-jump-admin"
```

...to the default_node_pool and user_node_pool configurations in the local.tf?

Thanks!

Michael

**Comment by thpang** [comment]
The nodes in the cluster are private with no external access. The IAC code base keeps it that way for security. You can use [Lens](https://k8slens.dev/) to access your nodes at this point in time.

I marked this as an enhancement as we're trying to find a secure way to access the nodes once you authenticated into the cluster. That is if you have cluster wide privileges. In a multi-tenancy env where you only have access to your namespace, node access will not be allowed so keep that in mind.

**Comment by shealym** [comment]
Yeah, I'm good with the private-network/no-external-access on the nodes...on AKS I've used something like this to get inside the cluster network:

```
kubectl run -it --rm aks-ssh --image=kroniak/ssh-client bash
```

...copied over the private key to the container, and accessed the nodes from there via ssh.  I was just looking to be able to do something similar on EKS after running viya4-iac-aws.

I'm expecting to have clients (especially in the SMB space) request us to admin their entire Viya4/K8S stack, and we'd definitely want access to the nodes for those clients (for validating host configs, tshooting issues, ensuring scripts fed in through the "custom_data" parameter run correctly, etc).  Is the auth based on cluster-wide admin privs a near-term feature?  If not, could propagating the ssh-key to the nodes possibly be an optional parameter until that feature is available?

**Comment by dhoucgitter** [comment]
@shealym, is this still an issue for you? With access to your cluster's admin kubeconfig file you should also be able to use the node-shell kubectl plugin installable using krew to shell into each of your nodes.
